# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Smoke
version:      1.19-RC2
version_from: lib/Test/Smoke.pm
installdirs:  site
requires:
    File::Spec:                    0.82
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
